[subnamespace] new chart

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -13,7 +13,7 @@ on:
 
 jobs:
   # https://github.com/bridgecrewio/checkov-action#example-usage-for-iac-and-sca
-  checkov:
+  checkov-github_actions:
     permissions:
       contents: read # for actions/checkout to fetch code
       security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
@@ -33,6 +33,61 @@ jobs:
           # This will add both a CLI output to the console and create a results.sarif file
           output_format: cli,sarif
           output_file_path: console,results.sarif
+          framework: github_actions
+          directory: .github
+
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v2
+
+        # Results are generated only on a success or failure
+        # this is required since GitHub by default won't run the next step
+        # when the previous one has failed. Security checks that do not pass will 'fail'.
+        # An alternative is to add `continue-on-error: true` to the previous step
+        # Or 'soft_fail: true' to checkov.
+        if: success() || failure()
+        with:
+          sarif_file: results.sarif
+
+  # https://github.com/bridgecrewio/checkov-action#example-usage-for-iac-and-sca
+  checkov-helm:
+    permissions:
+      contents: read # for actions/checkout to fetch code
+      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        chart:
+        - extra
+        - mailpit
+        - postgresql
+        - subnamespace
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
+      - uses: actions/checkout@v3
+
+      - name: Set up Helm
+        uses: azure/setup-helm@v3
+
+      - name: Build
+        run: |
+          for chart in charts/*; do
+            helm dep build "$chart";
+          done
+
+      - name: Checkov GitHub Action
+        uses: bridgecrewio/checkov-action@v12
+        with:
+          # This will add both a CLI output to the console and create a results.sarif file
+          output_format: cli,sarif
+          output_file_path: console,results.sarif
+          framework: helm
+          directory: charts/${{ matrix.chart }}
 
       - name: Upload SARIF file
         uses: github/codeql-action/upload-sarif@v2
@@ -57,13 +112,10 @@ jobs:
 
       - name: Set up Helm
         uses: azure/setup-helm@v3
-        with:
-          version: v3.11.2
 
       - uses: actions/setup-python@v4
         with:
-          python-version: '3.9'
-          check-latest: true
+          python-version: "3.11"
 
       - name: Set up chart-testing
         uses: helm/chart-testing-action@v2
