add kubelinter

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -61,10 +61,10 @@ jobs:
     strategy:
       matrix:
         chart:
-        - extra
-        - mailpit
-        - postgresql
-        - subnamespace
+          - extra
+          - mailpit
+          - postgresql
+          - subnamespace
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -77,10 +77,7 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Build
-        run: |
-          for chart in charts/*; do
-            helm dep build "$chart";
-          done
+        run: helm dep build "charts/${{ matrix.chart }}"
 
       - name: Checkov GitHub Action
         uses: bridgecrewio/checkov-action@v12
@@ -135,6 +132,52 @@ jobs:
       - name: Run chart-testing (lint)
         if: steps.list-changed.outputs.changed == 'true'
         run: ct lint --target-branch ${{ github.event.repository.default_branch }}
+
+  kube-linter:
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        chart:
+          #- extra
+          - mailpit
+          #- postgresql
+          #- subnamespace
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Set up Helm
+        uses: azure/setup-helm@v3
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build chart
+        run: helm dep build "charts/${{ matrix.chart }}"
+
+      - name: Scan yaml files with kube-linter
+        uses: stackrox/kube-linter-action@v1.0.4
+        id: kube-linter-action-scan
+        with:
+          # Adjust this directory to the location where your kubernetes resources and helm charts are located.
+          directory: charts/${{ matrix.chart }}
+          # The following two settings make kube-linter produce scan analysis in SARIF format which would then be
+          # made available in GitHub UI via upload-sarif action below.
+          format: sarif
+          output-file: kube-linter.sarif
+
+      - name: Upload SARIF report files to GitHub
+        uses: github/codeql-action/upload-sarif@v2
+
+        # Results are generated only on a success or failure
+        # this is required since GitHub by default won't run the next step
+        # when the previous one has failed. Security checks that do not pass will 'fail'.
+        # An alternative is to add `continue-on-error: true` to the previous step
+        # Or 'soft_fail: true' to checkov.
+        if: success() || failure()
+        with:
+          # Path to SARIF file relative to the root of the repository
+          sarif_file: kube-linter.sarif
 
   # https://github.com/aquasecurity/trivy-action#scan-ci-pipeline-w-trivy-config
   trivy:
